name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{vars.IMAGE_NAME}}

jobs:
  dependencies-check: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm ci

  build:
    needs: dependencies-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME}}:${{ github.sha }} .

      - name: Save Image 
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker save -o mi-imagen.tar ${{ env.IMAGE_NAME}}:${{github.sha}}  

      - name : Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: mi-imagen.tar

  escaneoImagenes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i mi-imagen.tar

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME}}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'